/**
 * OWNER: teammate C (T-19).
 *
 * DONE:  narration generated by Gemini TTS through /api/speak, cached for the
 *        session, with playback speed, stop, and a fallback to the device's
 *        own voice when the model cannot be reached.
 * TODO:  nothing structural.
 *
 * ── Why there is still a fallback ──────────────────────────────────────────
 * The model voice is the product's voice, and it is what plays whenever the
 * request succeeds. But a visitor standing in front of a building on weak
 * mobile data should hear the story rather than nothing, so a failed request
 * falls through to the browser's built-in speech. The caller is told which one
 * played, so the UI can say so rather than pretending.
 *
 * Nothing here writes text. It reads back exactly the sourced facts it was
 * handed — see the note at the top of api/speak.ts.
 */

import type { Lang } from './types';

export type SpeechSource = 'ai' | 'device';

export interface SpeakOptions {
  text: string;
  lang: Lang;
  /** One of the ids in lib/voices.ts. */
  voiceId: string;
  /** 0.5 slow — 1 normal — 1.5 fast. */
  rate?: number;
  onEnd?: () => void;
}

export interface SpeakHandle {
  /** Which voice actually played. */
  source: SpeechSource;
  /** True when the text was longer than the server will read in one go. */
  truncated: boolean;
}

/**
 * Generated audio, kept for the session.
 *
 * The same landmark, language and voice always produce the same audio, and
 * each clip costs a model call and a couple of megabytes. Replaying a story,
 * or coming back to it, should cost neither.
 */
const cache = new Map<string, string>();

let current: HTMLAudioElement | null = null;

function cacheKey(text: string, voiceId: string, lang: Lang): string {
  // The text itself is the identity — it changes when the facts change.
  return `${lang}:${voiceId}:${text.length}:${text.slice(0, 120)}`;
}

export function isSpeechAvailable(): boolean {
  return typeof window !== 'undefined';
}

/** Stops whatever is playing, from either source. */
export function stopSpeaking(): void {
  if (current) {
    current.pause();
    current.src = '';
    current = null;
  }
  if (typeof window !== 'undefined' && 'speechSynthesis' in window) {
    window.speechSynthesis.cancel();
  }
}

/** The device's own voice. Used only when the model could not be reached. */
function speakOnDevice({ text, lang, rate = 1, onEnd }: SpeakOptions): SpeakHandle {
  if (!('speechSynthesis' in window)) {
    onEnd?.();
    return { source: 'device', truncated: false };
  }

  const utterance = new SpeechSynthesisUtterance(text);
  utterance.lang = lang === 'ar' ? 'ar-SA' : 'en-US';
  utterance.rate = rate;
  utterance.onend = () => onEnd?.();
  utterance.onerror = () => onEnd?.();
  window.speechSynthesis.speak(utterance);

  return { source: 'device', truncated: false };
}

/**
 * Reads text aloud in the chosen voice.
 *
 * Stops anything already playing first, so two taps never overlap. Resolves
 * once playback has *started*; `onEnd` fires when it finishes.
 */
export async function speak(options: SpeakOptions): Promise<SpeakHandle> {
  const { text, lang, voiceId, rate = 1, onEnd } = options;

  stopSpeaking();
  if (!text.trim()) {
    onEnd?.();
    return { source: 'ai', truncated: false };
  }

  const key = cacheKey(text, voiceId, lang);
  let truncated = false;

  try {
    let src = cache.get(key);

    if (!src) {
      const response = await fetch('/api/speak', {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ text, voice_id: voiceId, lang }),
      });

      if (!response.ok) {
        const detail = await response.json().catch(() => ({}));
        throw new Error(detail.error ?? `Speech failed (${response.status}).`);
      }

      const data = (await response.json()) as { audio?: string; truncated?: boolean };
      if (!data.audio) throw new Error('No audio came back.');

      truncated = Boolean(data.truncated);
      src = data.audio;
      cache.set(key, src);
    }

    const audio = new Audio(src);
    audio.playbackRate = rate;
    audio.onended = () => {
      current = null;
      onEnd?.();
    };
    audio.onerror = () => {
      current = null;
      onEnd?.();
    };

    current = audio;
    await audio.play();
    return { source: 'ai', truncated };
  } catch (err) {
    // Weak signal, no key, or a model that refused. Say the words anyway.
    console.warn('[speech] falling back to the device voice:', err);
    return speakOnDevice(options);
  }
}

/** True while audio from either source is playing. */
export function isSpeaking(): boolean {
  if (current && !current.paused) return true;
  return typeof window !== 'undefined' && 'speechSynthesis' in window
    ? window.speechSynthesis.speaking
    : false;
}
